import numpy as np

from tfg.games import BLACK, WHITE


# TODO implement multi dim option
class NeuralNetworkAdapter:
    """Abstract class with methods to convert an observation to network input
    (matching input_shape attribute) and its output (with output_shape shape)
    to an action.

    This class should not be used directly, but rather should be extended for
    every game.

    """

    def __init__(self, input_shape, output_shape):
        """
        Args:
            input_shape ((int, int, int)): Shape of the arrays returned by
                to_input. Used to set neural network's input shape.
            output_shape (int or (int, int, int)): Shape of the arrays
                outputted by neural network's policy head and passed as
                argument of from_output. If int, the neural network will use
                a dense layer as output with output_shape neurons. If tuple,
                a convolution with the given shape will be used instead.
        """
        self.input_shape = input_shape
        self.output_shape = output_shape

    # TODO might need previous observations as they do in AlphaZero
    def to_input(self, observation, to_play):
        """Converts an observation given by a tfg.games.GameEnv to a valid
        input for the neural network with shape input_shape.

        Args:
            observation (object): Observation generated by a tfg.games.GameEnv.
            to_play (int): The player (BLACK or WHITE) to play in the given
                state.

        Returns:
            numpy.ndarray: Valid input for the neural network.

        """
        raise NotImplementedError

    def to_indices(self, action):
        """Converts a valid action to indices to access a probability array
        with shape output_shape.

        Args:
            action (object): Action generated by the game.

        Returns:
            (int or (int, int, int)): A valid index or indices representing
                the given action in the policy head output.

        """
        raise NotImplementedError


class TicTacToeAdapter(NeuralNetworkAdapter):

    def __init__(self):
        super(TicTacToeAdapter, self).__init__((3, 3, 3), 9)

    def to_input(self, observation, to_play):
        array = np.zeros(shape=self.input_shape)
        array[observation == WHITE, 0] = 1
        array[observation == BLACK, 1] = 1
        array[..., 2] = 0 if to_play == WHITE else 1
        return array

    def to_indices(self, action):
        return action
